### ISSUE TITLE
Bug id folder

### ISSUE THREAD

**Issue by Stolker** [posborne/putio-sync#25]
Hi,
I install your script on my raspberry pi 2.
But I run the script with id of folder I would like to download, it download all file on my account.

Thx for help

**Comment by posborne** [comment]
The directory specified is where files should be downloaded to on your local device and not on the put.io service.  I'll consider this a feature request for the latter.

**Comment by Stolker** [comment]
Ahhhh  ok
Sorry, I don't understand when i read readme X)
Thx,
